### ISSUE TITLE
[feat/fix] 重构返回值使得报错信息明确

### ISSUE THREAD

**Issue by lanbinshijie** [OpenTeensCore/backend-oauth#10]
这段代码还是使用了True和False的返回值，如果返回false的分支较多，我觉得有必要可以返回一个标识符来告诉用户具体的问题，是白名单亦或者其他，比如多加一个返回值负责返回comment。

https://github.com/OpenTeensCore/backend-oauth/blob/62d5e26dc1be3bedfc0ba18e9a86bcddcada547d/utils/main.go#L77-L83

**Comment by BernieHuang2008** [comment]
这些都是邮箱不合法，没啥大区别。

不过可能unsupported domain需要提示一下哈？

**Comment by lanbinshijie** [comment]
> 不过可能unsupported domain需要提示一下哈？

是滴，我觉得invalid和unsupport可以区分下

**Comment by BernieHuang2008** [comment]
可以，明天我来改
