### ISSUE TITLE
[chore] 重构项目名

### ISSUE THREAD

**Issue by lanbinshijie** [OpenTeensCore/backend-oauth#13]
把整个仓库的名字改成`openteens-backend`吧，也符合readme中写的

https://github.com/OpenTeensCore/backend-oauth/blob/62d5e26dc1be3bedfc0ba18e9a86bcddcada547d/README.md?plain=1#L20-L28

**Comment by BernieHuang2008** [comment]
ok，记得在本地git上改一下源
