### ISSUE TITLE
考虑将默认分支更改为 dev 以优化 Pull Request 流程

### ISSUE THREAD

**Issue by BernieHuang2008** [OpenTeensCore/backend-oauth#6]
要不要把默认分支改成dev？要不然pr的时候顺手就点成main了。

可以将 main 视为一个发布（release）分支，也就是正式版本。只有当 dev 的代码成熟时，才手动将其同步到 main 分支。

这样可以确保 main 分支上的代码始终是稳定和可靠的。

这样的话main也不常用了，可以把默认分支改为dev

**Comment by lanbinshijie** [comment]
可以，我现在改一下。

**Comment by lanbinshijie** [comment]
诶不对，我没有权限改（笑哭）

@BernieHuang2008 你改下吧

**Comment by lanbinshijie** [comment]
@BernieHuang2008 你看一下我在#11 中写的那个方案，可以的话就把这个not planned吧。

**Comment by BernieHuang2008** [comment]
我觉得还是要把dev弄成默认，要不然git prune根本没用
