### ISSUE TITLE
[Style] 关于api

### ISSUE THREAD

**Issue by BernieHuang2008** [OpenTeensCore/backend-oauth#8]
代码太散，这里就用我的api docs来标示位置吧

> xx xx
> x 1 x
> xx xx

这两个地方的code重复返回了http状态码，不太符合restful规范
https://github.com/OpenTeensCore/backend-oauth/blob/064c1d7647bc6e9da85fd63e5c23dc8aa0e0677c/docs/apidocs-v1.yaml#L71-L73
https://github.com/OpenTeensCore/backend-oauth/blob/064c1d7647bc6e9da85fd63e5c23dc8aa0e0677c/docs/apidocs-v1.yaml#L88-L89

> xx xx
> x 2 x
> xx xx

这个应该是个typo，状态码是200，code却是400
https://github.com/OpenTeensCore/backend-oauth/blob/064c1d7647bc6e9da85fd63e5c23dc8aa0e0677c/docs/apidocs-v1.yaml#L72

> xx xx
> x 3 x
> xx xx

这里我有个建议，可以不用返回所有info。比如说在GET中新添加一个字段叫做`info`，e.g. `?info=phone+email`，然后只返回手机号和邮箱。

https://github.com/OpenTeensCore/backend-oauth/blob/064c1d7647bc6e9da85fd63e5c23dc8aa0e0677c/docs/apidocs-v1.yaml#L91-L101

比如说下面是我那个版本的思路：
### 请求:
|字段与类型|备注|
|-|-|
|token: `str`|以 cookie（`token=xxx;`）的形式存在 header 中|
|\<uid>: `int`|用户唯一id|
|\<typequery>: `str`|URI query参数|

示例：
```
/account/info/24?r=phone+username

示例为获取uid为24的用户的 手机号 和 用户名 信息。
```
### 返回:
示例：
```json
200 OK
{
  "info": {
    "uname": "Bernie", 
    "phone": 12345678910
  }
}
```
```json
400 Bad Request
{
  "error": "Invalid uid"
}
```
|字段|含义与备注|
|-|-|
|error: `str`|错误消息|
|value: `json`|查询结果，以查询信息的字段名为key。各字段数据类型可能不同。|

**Comment by BernieHuang2008** [comment]
这些问题我明天改把，有一个俩状态码的

https://github.com/OpenTeensCore/backend-oauth/blob/064c1d7647bc6e9da85fd63e5c23dc8aa0e0677c/docs/apidocs-v1.yaml#L72

这个到底啥意思

**Comment by lanbinshijie** [comment]
系统问题，按理说应该不会发生，但是当时开发就留着这个else分支了，应该一辈子不会被触发、、、

**Comment by BernieHuang2008** [comment]
e那我明天删了吧，或者标记一下？哪个好

**Comment by BernieHuang2008** [comment]
这块也在controller里面，我们俩同时改的话麻烦，要不等你先重构完？
